In [1]:
import numpy as np

# Create a NumPy array
my_array = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

# Accessing Array Properties
array_shape = my_array.shape  # Shape of the array (dimensions)
array_size = my_array.size    # Size of the array (total number of elements)
array_dtype = my_array.dtype  # Data type of the elements in the array

# Printing Array Properties
print("Array:")
print(my_array)
print("\nArray Shape:", array_shape)
print("Array Size:", array_size)
print("Array Data Type:", array_dtype)


Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Array Shape: (3, 3)
Array Size: 9
Array Data Type: int64


In [2]:
import numpy as np

# Create two NumPy arrays
array1 = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

array2 = np.array([[9, 8, 7],
                   [6, 5, 4],
                   [3, 2, 1]])

# Perform Array Operations
array_addition = array1 + array2
array_subtraction = array1 - array2
array_multiplication = array1 * array2
array_division = array1 / array2

# Printing Results
print("Array 1:")
print(array1)
print("\nArray 2:")
print(array2)

print("\nArray Addition:")
print(array_addition)

print("\nArray Subtraction:")
print(array_subtraction)

print("\nArray Multiplication:")
print(array_multiplication)

print("\nArray Division:")
print(array_division)

Array 1:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Array 2:
[[9 8 7]
 [6 5 4]
 [3 2 1]]

Array Addition:
[[10 10 10]
 [10 10 10]
 [10 10 10]]

Array Subtraction:
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]

Array Multiplication:
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]

Array Division:
[[0.11111111 0.25       0.42857143]
 [0.66666667 1.         1.5       ]
 [2.33333333 4.         9.        ]]


In [5]:
import numpy as np

# Generate two random 5x5 matrices
matrix1 = np.random.rand(5, 5)
matrix2 = np.random.rand(5, 5)

# Perform matrix multiplication
result_matrix1 = np.dot(matrix1, matrix2)

# Alternatively, you can use the @ operator for matrix multiplication
result_matrix2 = matrix1 @ matrix2

# Perform element-wise multiplication
result_matrix3 = matrix1 * matrix2

print("Matrix 1:")
print(matrix1)
print("\nMatrix 2:")
print(matrix2)
print("\nResult Matrix1:")
print(result_matrix1)
print("\nResult Matrix2:")
print(result_matrix2)
print("\nResult Matrix3:")
print(result_matrix3)

Matrix 1:
[[0.11375134 0.59385753 0.95056089 0.88470112 0.36920745]
 [0.70330434 0.47158135 0.50950612 0.39875395 0.8506669 ]
 [0.28143272 0.51721639 0.90002967 0.80633582 0.95898317]
 [0.78550522 0.44556475 0.87063692 0.15821857 0.9176677 ]
 [0.39616018 0.49859386 0.79323223 0.24351393 0.37399191]]

Matrix 2:
[[0.25197668 0.85783221 0.51405033 0.64106111 0.4893183 ]
 [0.14552214 0.45185413 0.6776783  0.41929789 0.31264726]
 [0.0283149  0.21141357 0.84100064 0.12170041 0.40641155]
 [0.87361665 0.40741922 0.80114702 0.99388779 0.85181818]
 [0.19169379 0.37712256 0.291272   0.97894457 0.9583435 ]]

Result Matrix1:
[[0.98566155 1.06655873 2.07665606 1.67833569 1.73507953]
 [0.77169409 1.40738532 1.67684523 1.93967365 1.85354442]
 [1.05992469 1.35557782 2.17742093 2.24701598 2.27108572]
 [0.60155411 1.4697609  1.83199223 1.85193539 1.89171791]
 [0.47926962 0.97308376 1.51266515 1.1677018  1.23795348]]

Result Matrix2:
[[0.98566155 1.06655873 2.07665606 1.67833569 1.73507953]
 [0.77169409 1

In [3]:
import numpy as np

# Set the random seed to 42
np.random.seed(42)

# Generate random numbers
random_numbers1 = np.random.rand(5)
print(random_numbers1)

# Reset the seed to 42 and generate again
np.random.seed(42)
random_numbers2 = np.random.rand(5)
print(random_numbers2)


[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]
[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]
